name: NEXRAD
datapath: /store/msrad/radar/NEXRAD/KATX/
path_convention: ODIM
cosmopath: /store/msrad/cosmo/
loadbasepath: /store/msrad/radar/pyrad_products/
loadname: NEXRAD
saveimgbasepath: /store/msrad/radar/pyrad_products/
imgformat: png
configpath: /users/wolfensb/pyrad/config/
locationConfigFile: /users/wolfensb/pyrad/config/processing/nexrad_loc.txt
productConfigFile: /users/wolfensb/pyrad/config/processing/nexrad_prod.txt
