name: rad4alp_IQA
datapath: /store/msrad/radar/rad4alp/rawdata/
metranet_read_lib: python
iqpath: /store/msrad/radar/rad4alp/iqdata/
cosmopath: /store/msrad/cosmo/cosmo1/
loadbasepath: /store/msrad/radar/pyrad_products/
loadname: rad4alp_IQA
smnpath: /data/meteo_products/SMNRetrieve/
disdropath: /data/scattering/dsd_ts/
saveimgbasepath: /store/msrad/radar/pyrad_products/
imgformat: png
configpath: /users/wolfensb/pyrad/config/
locationConfigFile: /users/wolfensb/pyrad/config/processing/rad4alp_IQA_loc.txt
productConfigFile: /users/wolfensb/pyrad/config/processing/rad4alp_IQA_prod.txt
