name: rad4alp_hydro_PLA
datapath: /store/msrad/radar/rad4alp/rawdata/
cosmopath: /store/msrad/cosmo/
loadbasepath: /store/msrad/radar/pyrad_products/
loadname: rad4alp_hydro_PHL
smnpath: /data/meteo_products/SMNRetrieve/
disdropath: /data/scattering/dsd_ts/
saveimgbasepath: /store/msrad/radar/pyrad_products/
imgformat: png
configpath: /users/wolfensb/pyrad/config/
locationConfigFile: /users/wolfensb/pyrad/config/processing/rad4alp_hydro_PLA_loc.txt
productConfigFile: /users/wolfensb/pyrad/config/processing/rad4alp_hydro_PLA_prod.txt
