name: rad4alp_wind_PLA
datapath: /store/msrad/radar/rad4alp/rawdata/
cosmopath: /store/msrad/cosmo/cosmo1/
dempath: /store/msrad/radar/rad4alp/visibRad4Alp/
smnpath: /data/meteo_products/SMNRetrieve/
disdropath: /data/scattering/dsd_ts/
saveimgbasepath: /store/msrad/radar/pyrad_products/
saveimg: 1
imgformat: png
configpath: /users/wolfensb/pyrad/config/
locationConfigFile: /users/wolfensb/pyrad/config/processing/rad4alp_wind_PLA_loc.txt
productConfigFile: /users/wolfensb/pyrad/config/processing/rad4alp_wind_PLA_prod.txt
