name: gva_wind_lidar_rhi
datapath: /store/msrad/radar/GENEVA/wind_lidar/
path_convention: ODIM
psrpath: /store/msrad/radar/DX50/psr/
cosmopath: /store/msrad/cosmo/
loadbasepath: /store/msrad/radar/pyrad_products/
loadname: gva_wind_lidar_rhi
saveimgbasepath: /store/msrad/radar/pyrad_products/
imgformat: png
configpath: /users/wolfensb/pyrad/config/
locationConfigFile: /users/wolfensb/pyrad/config/processing/gva_wind_lidar_rhi_loc.txt
productConfigFile: /users/wolfensb/pyrad/config/processing/gva_wind_lidar_rhi_prod.txt
