ScanList:
- ppi_97_100m
ppiImageConfig:
  xsize: 10.0
  ysize: 8.0
  xmin: 0.0
  xmax: 15.0
  ymin: -5.0
  ymax: 5.0
sunhitsImageConfig:
  xsize: 8.0
  ysize: 7.0
  azmin: -2.0
  azmax: 2.0
  elmin: -2.0
  elmax: 2.0
  azres: 0.1
  elres: 0.1
rhiImageConfig:
  xsize: 9.0
  ysize: 7.0
  xmin: 0.0
  xmax: 15.0
  ymin: 0.0
  ymax: 8.0
