dataSetList:
- l0:RAD2COSMO
- l1:TEMP
RAD2COSMO:
  type: COSMO_COORD
  datatype:
  - RAD4ALP:dBZ
  products:
    rad2cosmo:
      type: SAVEVOL
      voltype: cosmo_index
TEMP:
  type: COSMO_LOOKUP
  datatype:
  - RAD4ALP:dBZ
  cosmo_type: TEMP
  regular_grid: 0
  lookup_table: 0
  MAKE_GLOBAL: 1
  products:
    SAVEVOL_TEMP:
      type: SAVEVOL
      voltype: TEMP
ZH:
  type: RAW
  datatype: RAD4ALP:dBZ
  products:
    EL001:
      type: PPI_IMAGE
      anglenr: 2
      voltype: dBZ
    AZ093:
      type: PSEUDORHI_IMAGE
      angle: 93.0
      AziTol: 1.0
      voltype: dBZ
ZH_TIME_HEIGHT:
  type: TIME_HEIGHT
  datatype: RAD4ALP:dBZ
  lon: 9.343
  lat: 47.249
  latlon_tol: 0.005
  hres: 500.0
  hmax: 12000.0
  products:
    TIME_HEIGHT:
      qvp_type: final
      type: TIME_RANGE
      anglenr: 0
      voltype: dBZ
    SAVEVOL:
      type: SAVEVOL
      voltype: dBZ
ZH_grid:
  type: GRID
  datatype: RAD4ALP:dBZ
  wfunc: NEAREST
  gridConfig:
    xmin: 0.0
    xmax: 100.0
    ymin: -50.0
    ymax: 60.0
    zmin: 0.0
    zmax: 12000.0
    hres: 500.0
    vres: 200.0
    altorig: 0.0
  products:
    LATLON:
      type: CROSS_SECTION
      voltype: dBZ
      coord1:
        lat: 47.18
        lon: 9.25
      coord2:
        lat: 47.61
        lon: 9.7
    SURFACE:
      type: SURFACE_IMAGE
      voltype: dBZ
      level: 25
SNRh:
  type: SNR
  datatype:
  - RAD4ALP:dBZ
  - RAD4ALP:Nh
  output_type: SNRh
  MAKE_GLOBAL: 1
RhoHV:
  type: RHOHV_CORRECTION
  datatype:
  - RAD4ALP:uRhoHV
  - RAD4ALP:ZDR
  - RAD4ALP:Nh
  - RAD4ALP:Nv
  - PROC:SNRh
  MAKE_GLOBAL: 1
dBm:
  type: PWR
  datatype:
  - RAD4ALP:dBZ
  MAKE_GLOBAL: 0
  products:
    EL001:
      type: PPI_IMAGE
      anglenr: 2
      voltype: dBm
    AZ093:
      type: PSEUDORHI_IMAGE
      angle: 93.0
      AziTol: 1.0
      voltype: dBm
echoID:
  type: SAN
  datatype:
  - RAD4ALP:dBZ
  - RAD4ALP:ZDR
  - RAD4ALP:uPhiDP
  - PROC:RhoHV
  MAKE_GLOBAL: 1
echoFilter:
  type: ECHO_FILTER
  datatype:
  - PROC:echoID
  - RAD4ALP:dBZ
  - RAD4ALP:ZDR
  - PROC:RhoHV
  - RAD4ALP:uPhiDP
  echo_type: 3
  MAKE_GLOBAL: 1
  products:
    EL001_RhoHVc:
      type: PPI_IMAGE
      anglenr: 2
      voltype: RhoHVc
    AZ093_RhoHVc:
      type: PSEUDORHI_IMAGE
      angle: 93.0
      AziTol: 1.0
      voltype: RhoHVc
    SAVEVOL_RhoHVc:
      type: SAVEVOL
      voltype: RhoHVc
SNRFilter:
  type: SNR_FILTER
  datatype:
  - PROC:SNRh
  - PROC:PhiDPc
  SNRmin: 10.0
  MAKE_GLOBAL: 1
PhiDPc_smooth2w:
  type: PHIDP_SMOOTH_2W
  datatype:
  - PROC:PhiDPc
  - PROC:dBZc
  rmin: 1000.0
  rmax: 50000.0
  rcell: 1000.0
  Zmin: 20.0
  Zmax: 40.0
  rwinds: 1000.0
  rwindl: 3000.0
  Zthr: 40.0
  MAKE_GLOBAL: 1
  products:
    EL001:
      type: PPI_IMAGE
      anglenr: 2
      voltype: PhiDPc
    AZ093:
      type: PSEUDORHI_IMAGE
      angle: 93.0
      AziTol: 1.0
      voltype: PhiDPc
    SAVEVOL_PhiDPc:
      type: SAVEVOL
      voltype: PhiDPc
KDPc_Vulpiani:
  type: PHIDP_KDP_VULPIANI
  datatype:
  - PROC:PhiDPc
  rwind: 1000.0
  n_iter: 6
  interp: 0
  parallel: 0
  get_phidp: 0
  MAKE_GLOBAL: 1
  products:
    EL001:
      type: PPI_IMAGE
      anglenr: 2
      voltype: KDPc
    AZ093:
      type: PSEUDORHI_IMAGE
      angle: 93.0
      AziTol: 1.0
      voltype: KDPc
    SAVEVOL_KDPc:
      type: SAVEVOL
      voltype: KDPc
Att_ZPhi:
  type: ATTENUATION
  datatype:
  - PROC:dBZc
  - PROC:ZDRc
  - PROC:PhiDPc
  - PROC:TEMP
  ATT_METHOD: ZPhi
  fzl: 2000.0
  MAKE_GLOBAL: 1
  products:
    EL001_dBZc:
      type: PPI_IMAGE
      anglenr: 2
      voltype: dBZc
    AZ093_dBZc:
      type: PSEUDORHI_IMAGE
      angle: 93.0
      AziTol: 1.0
      voltype: dBZc
    EL001_ZDRc:
      type: PPI_IMAGE
      anglenr: 2
      voltype: ZDRc
    AZ093_ZDRc:
      type: PSEUDORHI_IMAGE
      angle: 93.0
      AziTol: 1.0
      voltype: ZDRc
    SAVEVOL_dBZc:
      type: SAVEVOL
      voltype: dBZc
    SAVEVOL_ZDRc:
      type: SAVEVOL
      voltype: ZDRc
ZHc_TIME_HEIGHT:
  type: TIME_HEIGHT
  datatype: PROC:dBZc
  lon: 9.343
  lat: 47.249
  latlon_tol: 0.005
  hres: 500.0
  hmax: 12000.0
  products:
    TIME_HEIGHT:
      qvp_type: final
      type: TIME_RANGE
      anglenr: 0
      voltype: dBZc
    SAVEVOL:
      type: SAVEVOL
      voltype: dBZc
hydroclass_entropy:
  type: HYDROCLASS
  datatype:
  - PROC:dBZc
  - PROC:ZDRc
  - PROC:RhoHVc
  - PROC:KDPc
  - PROC:TEMP
  HYDRO_METHOD: SEMISUPERVISED
  RADARCENTROIDS: A
  compute_entropy: 1
  output_distances: 1
  MAKE_GLOBAL: 1
  products:
    SAVEVOL_hydro:
      type: SAVEVOL
      voltype: hydro
    SAVEVOL_entropy:
      type: SAVEVOL
      voltype: entropy
    SAVEVOL_propAG:
      type: SAVEVOL
      voltype: propAG
    SAVEVOL_propCR:
      type: SAVEVOL
      voltype: propCR
    SAVEVOL_propLR:
      type: SAVEVOL
      voltype: propLR
    SAVEVOL_propRP:
      type: SAVEVOL
      voltype: propRP
    SAVEVOL_propRN:
      type: SAVEVOL
      voltype: propRN
    SAVEVOL_propVI:
      type: SAVEVOL
      voltype: propVI
    SAVEVOL_propWS:
      type: SAVEVOL
      voltype: propWS
    SAVEVOL_propMH:
      type: SAVEVOL
      voltype: propMH
    SAVEVOL_propIH:
      type: SAVEVOL
      voltype: propIH
    EL001_hydro:
      type: PPI_IMAGE
      anglenr: 2
      voltype: hydro
    AZ093_hydro:
      type: PSEUDORHI_IMAGE
      angle: 93.0
      AziTol: 1.0
      voltype: hydro
    EL001_entropy:
      type: PPI_IMAGE
      anglenr: 2
      voltype: entropy
    AZ093_entropy:
      type: PSEUDORHI_IMAGE
      angle: 93.0
      AziTol: 1.0
      voltype: entropy
    EL001_propAG:
      type: PPI_IMAGE
      anglenr: 2
      voltype: propAG
    AZ093_propAG:
      type: PSEUDORHI_IMAGE
      angle: 93.0
      AziTol: 1.0
      voltype: propAG
    EL001_propCR:
      type: PPI_IMAGE
      anglenr: 2
      voltype: propCR
    AZ093_propCR:
      type: PSEUDORHI_IMAGE
      angle: 93.0
      AziTol: 1.0
      voltype: propCR
    EL001_propLR:
      type: PPI_IMAGE
      anglenr: 2
      voltype: propLR
    AZ093_propLR:
      type: PSEUDORHI_IMAGE
      angle: 93.0
      AziTol: 1.0
      voltype: propLR
    EL001_propRP:
      type: PPI_IMAGE
      anglenr: 2
      voltype: propRP
    AZ093_propRP:
      type: PSEUDORHI_IMAGE
      angle: 93.0
      AziTol: 1.0
      voltype: propRP
    EL001_propRN:
      type: PPI_IMAGE
      anglenr: 2
      voltype: propRN
    AZ093_propRN:
      type: PSEUDORHI_IMAGE
      angle: 93.0
      AziTol: 1.0
      voltype: propRN
    EL001_propVI:
      type: PPI_IMAGE
      anglenr: 2
      voltype: propVI
    AZ093_propVI:
      type: PSEUDORHI_IMAGE
      angle: 93.0
      AziTol: 1.0
      voltype: propVI
    EL001_propWS:
      type: PPI_IMAGE
      anglenr: 2
      voltype: propWS
    AZ093_propWS:
      type: PSEUDORHI_IMAGE
      angle: 93.0
      AziTol: 1.0
      voltype: propWS
    EL001_propMH:
      type: PPI_IMAGE
      anglenr: 2
      voltype: propMH
    AZ093_propMH:
      type: PSEUDORHI_IMAGE
      angle: 93.0
      AziTol: 1.0
      voltype: propMH
    EL001_propIH:
      type: PPI_IMAGE
      anglenr: 2
      voltype: propIH
    AZ093_propIH:
      type: PSEUDORHI_IMAGE
      angle: 93.0
      AziTol: 1.0
      voltype: propIH
hydroclass_TIME_HEIGHT:
  type: TIME_HEIGHT
  datatype: PROC:hydro
  lon: 9.343
  lat: 47.249
  latlon_tol: 0.005
  hres: 500.0
  hmax: 12000.0
  products:
    TIME_HEIGHT:
      qvp_type: final
      type: TIME_RANGE
      anglenr: 0
      voltype: hydro
    SAVEVOL:
      type: SAVEVOL
      voltype: hydro
