name: MF
datapath: /utemp/mdso/figuerasiventuraj/SERVAL/serval_data_test/DATA_OUT/produits_binaires/
path_convention: ODIM
cosmopath: /utemp/mdso/figuerasiventuraj/SERVAL/serval_data_test/DATA_IN/reception_tempe/
loadbasepath: STRING /utemp/mdso/figuerasiventuraj/pyrad_products/
loadname: MF
saveimgbasepath: /utemp/mdso/figuerasiventuraj/pyrad_products/
imgformat:
- png
configpath: /users/wolfensb/pyrad/config/
locationConfigFile: /users/wolfensb/pyrad/config/processing/mf_mtcy_loc.txt
productConfigFile: /users/wolfensb/pyrad/config/processing/mf_prod.txt
